ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'STK_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BRANCH_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CITIZEN';
SELECT enum_range(NULL::"Role") AS updated_roles;
